reworked the second vignette
trendecon/trendecon pull request #48
Opened 2020-08-15 12:52 UTC by KKPMW

2020-08-15 12:53 UTC, KKPMW commented
Hello @christophsax and @a1exgo - updated the second vignette. Feel free to review and leave comments/suggestions.

2020-08-15 15:36 UTC, KKPMW commented
I will still have to make a few adjustments after seeing if 'inst' scripts are still necessary

2020-08-19 14:14 UTC, KKPMW commented
@a1exgo pinging to check if you got the previous notification

2020-08-19 20:20 UTC, a1exgo requested changes

2020-08-19 20:20 UTC, a1exgo commented on vignettes/daily-series.Rmd
> +In order to make meaningful comparisons over time such seasonal patterns, present within the data, need to be removed.
```suggestion
In order to make meaningful comparisons over time such seasonal patterns, present within the raw data, need to be filtered out.
```

2020-08-19 20:20 UTC, a1exgo commented on vignettes/daily-series.Rmd
> +Once the data for each keyword has been processed we end up with multiple time series - one for each keyword within the indicator.
```suggestion
Once the raw data for each keyword has been processed we end up with multiple time series - one for each keyword within the indicator.
```

2020-08-19 20:20 UTC, a1exgo commented on vignettes/daily-series.Rmd
> +Finally the prepared index is saved to a file:
```suggestion
Finally the prepared index is saved to a file in the data folder:
```

2020-08-19 20:20 UTC, a1exgo commented on vignettes/daily-series.Rmd
> +- To add new indicator "indicator": create a new script at `inst/script/indicator.R`.
```suggestion
- To add a new indicator "indicator": create a new script at `inst/script/indicator.R`.
```

2020-08-19 20:20 UTC, a1exgo commented on vignettes/daily-series.Rmd
> +`raw` folder holds all the data downloaded from Google, plus some transformations, such as seasonally adjusted or combined series.
```suggestion
`raw` folder holds all the data downloaded from Google that are automatically transformed by the `trendecon`package. The transformations include seasonal adjustments or combining multiple keywords related to the indicator.
```

2020-08-19 20:20 UTC, a1exgo commented on vignettes/daily-series.Rmd
> +So be careful, as this causes a lot of queries to Google.
This line made me insecure. You could add, why we should careful (blocking by the API?And yes, for how long?) Or could we delete it?

2020-08-20 20:24 UTC, a1exgo approved these changes
Hi @KKPMW , I looked into both commits and did some comments in #48 , as I was not able to review this one. Please let me know if I can help you further out.

2020-08-20 20:24 UTC, a1exgo commented on vignettes/daily-series.Rmd
> +If the data for a particular keyword is not yet available, `proc_keyword_init()` should be called instead.
the function downloaded time series (d,w,m) for the keyword "Insvolvenz". The function above, proc_keyword_latest I could not execute "could not find function "proc_keyword_latest". I guess this is to come?

2020-08-24 07:57 UTC, a1exgo commented on vignettes/daily-series.Rmd
> +`raw` folder holds all the data downloaded from Google, plus some transformations, such as seasonally adjusted or combined series.
I see! So there are the raw time series, and on top some with transformations if called. My bad. I think the sentence you had written is good.

2020-08-24 07:59 UTC, a1exgo commented on vignettes/daily-series.Rmd
> +So be careful, as this causes a lot of queries to Google.
I like the small addition!

2020-08-24 08:02 UTC, a1exgo commented on vignettes/daily-series.Rmd
> +If the data for a particular keyword is not yet available, `proc_keyword_init()` should be called instead.
great! thanks for the explanation and hint!

2020-08-24 09:08 UTC, KKPMW commented
Hello @a1exgo , if the pull request seems more or less OK to you now, then I will merge it. Of course after that we can still work on it if we see possible improvements.

2020-08-24 16:40 UTC, merged